dailyfresh/apps/cart/urls.py
from django.conf.urls import url
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^add$', CartAddView.as_view(), name='add'), # 购物车记录添加
    url(r'^$', CartInfoView.as_view(), name='show'), # 购物车页面显示
    url(r'^update$', CartUpdateView.as_view(), name='update'), # 购物车记录更新
    url(r'^delete$', CartDeleteView.as_view(), name='delete'), # 购物车记录删除
]

dailyfresh/apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'), # 首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'), # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'), # 列表页
]

dailyfresh/apps/user/urls.py
from django.conf.urls import url
from user.views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView,  AddressView, LogoutView # 导入视图类
from django.contrib.auth.decorators import login_required  # login_required登录验证装饰器

urlpatterns = [
    # url(r'^register$', views.register, name='register'),
    # url(r'^register_handle$', views.register_handle, name='register_handle'),
    # url(r'^login$', views.login, name='login'),

    url(r'^register$', RegisterView.as_view(), name='register'),  # 用户注册
    url(r'^active/(.*)$', ActiveView.as_view(), name='active'),  # 用户激活
    url(r'^login$', LoginView.as_view(), name='login'),  # 用户激活
    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 用户激活
    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户激活  使用登录验证
    url(r'^order$', UserOrderView.as_view(), name='order'),  # 用户激活
    url(r'^address$', AddressView.as_view(), name='address'),  # 用户激活

]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),  # 搜索
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^user/', include('user.urls', namespace='user')),  # 用户模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('orders.urls', namespace='order')),  # 订单模块
    url(r'^', include('goods.urls', namespace='goods')),  # 商品模块

]

dailyfresh/templates/layout/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {#        标题#}
        {% block title %}{% endblock title %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {#    js文件块#}
    {% block js %}
        <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock js %}

</head>
<body>
{#    欢迎信息#}
    {% block header_con %}
        <div class="header_con">
            <div class="header">
                <div class="welcome fl">欢迎来到天天生鲜!</div>
                <div class="fr">
                    {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                    {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                    {% endif %}
                    <div class="user_link fl">
                        <span>|</span>
                        <a href="{% url 'user:user' %}">用户中心</a>
                        <span>|</span>
                        <a href="{% url 'cart:show' %}">我的购物车</a>
                        <span>|</span>
                        <a href="{% url 'user:order' %}">我的订单</a>
                    </div>
                </div>
            </div>
        </div>
    {% endblock header_con %}

{#    搜索栏#}
    {% block search_bar %}
        <div class="search_bar clearfix">
            <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
            <div class="search_con fl">
                <form action="/search" method="get">
                    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                    <input type="button" class="input_btn fr" name="" value="搜索">
                </form>
            </div>
            {# 购物车 #}
            <div class="guest_cart fr">
                <a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
            </div>
        </div>
    {% endblock search_bar %}

    {% block body %}

    {% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#    网页底部html元素块#}
    {% block bottom %}{% endblock bottom %}
{#    网页底部引入文件块#}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

dailyfresh/templates/layout/base_list_detail.html
{% extends 'layout/base.html' %}
{% block body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for type in types %}
                    <li><a href="{% url 'goods:list' type.id 1 %}" class="fruit">{{ type.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>
{# 详情页、列表页主题内容#}
{% block main_content %}{% endblock main_content %}
{% endblock body %}

dailyfresh/templates/layout/base_no_cart.html
{% extends 'layout/base.html' %}
{% load staticfiles %}
{#    搜索栏#}
{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

dailyfresh/templates/layout/base_user_center.html
{% extends 'layout/base_no_cart.html' %}
{% block title %}
天天生鲜-用户中心
{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %} class="active" {% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == 'order' %} class="active" {% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %} class="active" {% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {#        右侧内容块#}
        {% block right_content %}{% endblock right_content %}
</div>
{% endblock body %}

dailyfresh/templates/layout/end.html
</body>
</html>

dailyfresh/templates/layout/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-注册</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</head>
<body>
{% block body %}

{% endblock body %}
</body>
</html>

dailyfresh/templates/layout/static_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {#        标题#}
        {% block title %}{% endblock title %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {#    js文件块#}
    {% block js %}
        <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock js %}

</head>
<body>
{#    欢迎信息#}
    {% block header_con %}
        <div class="header_con">
            <div class="header">
                <div class="welcome fl">欢迎来到天天生鲜!</div>
                <div class="fr">

                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>

                    <div class="user_link fl">
                        <span>|</span>
                        <a href="{% url 'user:user' %}">用户中心</a>
                        <span>|</span>
                        <a href="cart.html">我的购物车</a>
                        <span>|</span>
                        <a href="{% url 'user:order' %}">我的订单</a>
                    </div>
                </div>
            </div>
        </div>
    {% endblock header_con %}

{#    搜索栏#}
    {% block search_bar %}
        <div class="search_bar clearfix">
            <a href="/" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
            <div class="search_con fl">
                <input type="text" class="input_text fl" name="" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </div>
            <div class="guest_cart fr">
                <a href="#" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">1</div>
            </div>
        </div>
    {% endblock search_bar %}

    {% block body %}

    {% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#    网页底部html元素块#}
    {% block bottom %}{% endblock bottom %}
{#    网页底部引入文件块#}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>